### ISSUE TITLE
Possible to use with "Require touch"?

### ISSUE THREAD

**Issue by richardpeng** [robertoriv/alfred-yubikey-otp#1]
Would it be possible to make this script work with entries that are configured to require touch?

**Comment by robertoriv** [comment]
@richardpeng, I took a quick look at this, and I'm not sure how to handle that case yet. I pull the codes by executing:

```
rrivera-mac2:~ roberto$ ykman oath code
...
GitHub:robertoriv                             506918
GitHub(t):robertoriv              [Touch Credential]
```

Basically, I get a list of all the codes to present a list. When I do that, there's no interactive request to place the finger on the device. It just blurts out the item with `[Touch Credential]`.

In order to get the interactive prompt, you'd need to filter the list down, like so:

```
rrivera-mac2:~ roberto$ ykman oath code "(t)"
Touch your YubiKey...  
# it waits here for the touch
GitHub(t):robertoriv  370920
```

I'd need to pre-filter the list to a single candidate. 

I'll give this a shot in a few days.

**Comment by richardpeng** [comment]
There's also a ykman oath -s query to ensure a single match if that helps.

Thanks for looking into this.

**Comment by starcatmeow** [comment]
I have implemented this feature, and I'll send a pull request quickly, wish you can accept it,  @robertoriv  . Thanks!

**Comment by robertoriv** [comment]
@starcatmeow I'll check out your PR tomorrow. Thanks!

**Comment by robertoriv** [comment]
Version `v1.0.0` has been published with @starcatmeow's PR. It adds support for the "require touch" entries.

Note that this feature uses conditionals, which is a new feature in `Alfred v4.0` and a breaking change for previous versions of Alfred.
